name: flutter_redux_combine2
description: An add on for redux_flutter to add additional data to a typed reducer
version: 0.1.0
author: Adrian <atreeonhill@gmail.com>
homepage: https://github.com/twistedinferno/redux_combine2

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  redux: ">=3.0.0 <4.0.0"

dev_dependencies:
